### ISSUE TITLE
Parser is particular about comment format

### ISSUE THREAD

**Issue by recurry** [peej/tonic#187]
It seems that the Tonic parser is very particular about how comments are laid out. This may be something worth noting in the documentation because it can be confusing to a new user.

For example, this works fine:
```javascript
/**
 * My Resource Implementation
 * ------------------------------------
 * @uri foobar
 */
```
but this does not:
```javascript
/**************************************
 * My Resource Implementation
 * ------------------------------------
 * @uri foobar
 *************************************/
```
This can be really frustrating the first time you run into it - there's no error message generated that steers you to the root cause of the problem.

**Comment by peej** [comment]
Thanks for reporting this.

Unfortunately due to the way the PHP reflection API works, it only treats comments starting `/**<whitespace>` as doccomments, every other type of comment it discarded and not available to the reflector.

I've added some code to the resource metadata class to look within the source file itself if the reflector cannot find a doccomment by working its way backwards from the class definition. This should cause anything that looks remotely like a doccomment to be found and used.
