### ISSUE TITLE
Resource matching URI "http://api.fsm.lan/v1/user/password/reset" not found

### ISSUE THREAD

**Issue by justechn** [peej/tonic#198]
I am having trouble getting tonic to work in my app. 

in my resource file I have 

```
/**
 * API to manage user data
 *
 * @uri /v1/user/password/reset
 *
 */
```

![capture](https://cloud.githubusercontent.com/assets/1508662/11765899/186bd7c4-a12a-11e5-8619-7b32c6827d98.PNG)

As you can see in the screenshot. I am getting a $request->getUri() of http://api.fsm.lan/v1/user/password/reset and the $uriRegex is |^/v1/user/password/reset$| 

However when it runs the preg_match it does not find a match. if you go here https://regex101.com/r/kB9aN9/1 you can see that there are several problems with the regex. 

So why is tonic building a regex that will not match? Am I doing something wrong with the setup?

**Comment by peej** [comment]
The url should work for you, it's most likely something else wrong with your server configuration.

You can see how the regex matches here https://regex101.com/r/kB9aN9/2

A quick explanation:
- Tonic matches against the URL path, not the full URL, this is to allow resources to be portable between hostnames, protocol, etc.
- Tonic does not use the / delimiter for regex as URLs by design have many forward slashes in them, so instead we use the | pipe. You can use any character as the delimiter, as long as it doesn't appear unescaped within the regex, avoiding the / means we can avoid having to escape them all.

Hope this makes sense.

Check what $request->getUri() is returning, you'll probably find that something in your server setup is meaning the request URL is not ending up as you'd expect.

**Comment by justechn** [comment]
"Check what $request->getUri() is returning, you'll probably find that something in your server setup is meaning the request URL is not ending up as you'd expect."

Yeah, I already mentioned in the first post that $request->getUri() is returning the full url http://api.fsm.lan/v1/user/password/reset, so what setting in apache or PHP would cause it to return a full url instead of a url path?

**Comment by peej** [comment]
Look inside the $_SERVER superglobal and see which is variable is the URL path in your setup, Tonic tries to have a good default but it differs between setups. Once you find it you can pass it to the Request object when you instantiate it like this:

``` php
$request = new Request(array(
  'uri' => $_SERVER['REQUEST_URI']
));
```
